### PR TITLE
Micro-Reddit: Active Record Methods

### PR DESCRIPTION
**Pull request by ldelbel**
In this project, we built a micro-Reddit program, following the instructions on 'The Odin Project: Building with Active Record'. We followed the GitHub Workflow and used GitHub Actions for linting. 

The project is based on the use of databases, and our choice was to use Sqlite3 as suggested in the project instructions.
We used dbdiagram.io for planning the database models using sketches.

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @ldelbel and @ElijahTobs, great job with this project :+1: README file :100: PR very professional :slightly_smiling_face: We can create a user, post and comments :fireworks: Let us address these comments so we can get our project approved :slightly_smiling_face: Kindly find comments below:

- `Post` Let us validate our `post body`. Currently, we can create a post without the post body. Let us fix that
- Let us not modify our linter files, let use the recommended for this [project](https://github.com/microverseinc/linters-config/blob/master/ror/.github/workflows/linters.yml)

Kindly make these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by ElijahTobs** [comment]
I have added validation for the body as adviced by the TSE

**Comment by ElijahTobs** [comment]
The old .github/workflows folder was deleted alongside its content and new .github/workflows folder with linters.yml file was added and both (stylelint and rubocop) tests passed.

Thank you @addod19

**Review by christianotieno — APPROVED** [review]
# Project Approved 🍾 
## Congratulations team! All the required changes have been accomplished in this latest submission.
- You are free to merge these changes.
- All the very best in your next tasks!

### Christian Otieno (TSE)

**Pull request merged**
